server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/advertisements
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update


  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
springdoc:
  api-docs:
    path: /api-docs